Supply_Chain_Proj/inventory/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('item_stock/', views.item_stock, name = 'item-stock'),
    path('add_product/', views.add_product, name = 'add-product'),
    path('edit_item/<pk>/', views.edit_item, name = 'edit-item'),
    path('delete_item/<pk>/', views.delete_item, name = 'delete-item'),

    path('categories/', views.categories, name = 'categories'),

    path('categories/main/new', views.main_categories, name = 'main-categories'),
    path('categories/main/edit', views.edit_main_categories, name = 'edit-main-categories'),
    path('categories/main/delete/<pk>', views.delete_categories, name = 'delete-categories'),

    path('categories/sub/new', views.sub_categories, name = 'sub-categories'),
    path('categories/sub/edit', views.edit_sub_categories, name = 'edit-sub-categories'),
    path('categories/sub/delete/<pk>', views.delete_sub_categories, name = 'delete-sub-categories'),

]

Supply_Chain_Proj/supply_chain/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from user import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='user/forgot-password.html'),name='password-reset'),
    
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html'),name='password_reset_confirm'),

    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),name='password_reset_complete'),

    path('register/', user_views.register, name='register'),
    path('supplier/', include('supplier.urls')),
    path('customer/', include('customer.urls')),
    path('inventory/', include('inventory.urls')),
    path('transaction/', include('transaction.urls')),
    path('user/', include('user.urls')),

]

Supply_Chain_Proj/user/urls.py
from django.urls import path, include
from . import views


urlpatterns = [

    path('select_company_fiscal', views.select_company_fiscal, name = 'company-fiscal'),
    path('user_roles/<pk>', views.user_roles, name = 'user-roles'),
    path('user_list/', views.user_list, name = 'user-list'),
    path('user_roles/delete/<pk>', views.delete_user_roles, name = 'delete-user-roles'),
    path('user/edit/<pk>', views.edit_user, name = 'edit-user-roles'),
]

Supply_Chain_Proj/inventory/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    category_code = models.IntegerField()
    main = models.CharField(max_length = 100)

class SubCategory(models.Model):
    sub_category_code = models.IntegerField()
    sub = models.CharField(max_length = 100)
    main_category_id = models.ForeignKey(Category, models.SET_NULL, blank = True, null = True)


class Add_products(models.Model):
    product_code = models.CharField(max_length = 100, unique = True)
    product_name = models.CharField(max_length = 100)
    product_desc = models.TextField()
    unit = models.CharField(max_length = 100)
    type = models.CharField(max_length = 100)
    size = models.CharField(max_length = 100)
    opening_stock = models.DecimalField(max_digits = 8, decimal_places = 2)
    user_id = models.ForeignKey(User,models.SET_NULL, blank = True, null = True)
    main_category = models.CharField(max_length = 100)
    sub_category = models.CharField(max_length = 100)
    main_category_id = models.ForeignKey(Category, models.SET_NULL, blank = True, null = True)
    sub_category_id = models.ForeignKey(SubCategory, models.SET_NULL, blank = True, null = True)

Supply_Chain_Proj/user/models.py
from django.db import models
from django.contrib.auth.models import User


class UserRoles(models.Model):
    user_id = models.ForeignKey(User, models.SET_NULL,blank=True,null=True)
    form_id = models.IntegerField()
    form_name = models.CharField(max_length = 100)
    child_form = models.IntegerField()
    display = models.IntegerField(default='0')
    add = models.IntegerField(default='0')
    edit = models.IntegerField(default='0')
    delete = models.IntegerField(default='0')
    r_print = models.IntegerField(default='0')
    r_return = models.IntegerField(default='0')


class FiscalYear(models.Model):
    fiscal_year = models.CharField(max_length = 100)
    database_name = models.CharField(max_length = 100)
    is_current_year = models.IntegerField()

class Company_info(models.Model):
    company_name = models.CharField(max_length = 100)
    company_address = models.TextField()
    company_type = models.IntegerField()
    company_logo = models.TextField()
    phone_no = models.CharField(max_length = 100)
    mobile_no = models.CharField(max_length = 100)
    email = models.CharField(max_length = 100)
    website = models.CharField(max_length = 100)
    ntn = models.CharField(max_length = 100)
    stn = models.CharField(max_length = 100)
    cnic = models.CharField(max_length = 100)
    user_id = models.ForeignKey(User,models.SET_NULL, blank = True, null = True)

Supply_Chain_Proj/inventory/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from .models import (Add_products, Category, SubCategory)
from transaction.models import (PurchaseDetail, SaleDetail)
from itertools import chain
import json
from django.db import connection
from django.contrib import messages
from supplier.views import customer_roles,supplier_roles,transaction_roles,inventory_roles,report_roles
from django.db.models import Q
from django.contrib.auth.decorators import user_passes_test, login_required
from django.db.models import Q
from user.models import UserRoles
from django.core import serializers


def inventory_form_roles(user):
    userid = str(user.id)
    user_id = Q(user_id= userid)
    child_form = Q(child_form= 41)
    inventory_roles = UserRoles.objects.filter(user_id,child_form).first()
    return inventory_roles

def allow_inventory_display(user):
    user_id = Q(user_id = user.id)
    form_id = Q(form_id = 4)
    child_form = Q(child_form = 41)
    display = Q(display = 1)
    allow_role = UserRoles.objects.filter(user_id, form_id, child_form, display)
    if allow_role:
        return True
    else:
        return False


def allow_inventory_add(user):
    user_id = Q(user_id = user.id)
    form_id = Q(form_id = 4)
    child_form = Q(child_form = 41)
    add = Q(add = 1)
    allow_role = UserRoles.objects.filter(user_id, form_id, child_form, add)
    if allow_role:
        return True
    else:
        return False

def allow_inventory_edit(user):
    user_id = Q(user_id = user.id)
    form_id = Q(form_id = 4)
    child_form = Q(child_form = 41)
    edit = Q(edit = 1)
    allow_role = UserRoles.objects.filter(user_id, form_id, child_form, edit)
    if allow_role:
        return True
    else:
        return False

def allow_inventory_delete(user):
    user_id = Q(user_id = user.id)
    form_id = Q(form_id = 4)
    child_form = Q(child_form = 41)
    delete = Q(delete = 1)
    allow_role = UserRoles.objects.filter(user_id, form_id, child_form, delete)
    if allow_role:
        return True
    else:
        return False

def allow_inventory_shop(user):
    user_id = Q(user_id = 2)
    form_id = Q(form_id = 4)
    child_form = Q(child_form = 41)
    r_print = Q(r_print = 1)
    allow_role = UserRoles.objects.filter(user_id, form_id, child_form, r_print)
    print(allow_role)
    if allow_role:
        return True
    else:
        return False


@login_required
@user_passes_test(allow_inventory_display)
def item_stock(request):
    permission = inventory_form_roles(request.user)
    allow_customer_roles = customer_roles(request.user)
    allow_supplier_roles = supplier_roles(request.user)
    allow_transaction_roles = transaction_roles(request.user)
    allow_inventory_roles = inventory_roles(request.user)
    cursor = connection.cursor()
    cursor.execute('''Select itemID,Size,item_code, item_name,Item_description,Unit,Size,SUM(quantity) As qty, main_category, sub_category From (
                    Select 'Opening Stock' As TranType,ID As ItemID, Size,Product_Code As Item_Code,Product_Name As Item_name,Product_desc As Item_description,Unit As unit,Opening_Stock as Quantity, main_category, sub_category
                    From inventory_add_products
                    union all
                    Select 'Purchase' As TranType,P.ID As ItemID,P.Size,P.Product_Code,P.Product_name,P.Product_desc,P.unit,Quantity,P.main_category, P.sub_category
                    From transaction_purchasedetail H Inner join inventory_add_products P On H.item_id_id = P.id
                    union All
                    Select 'Purchase Return' As TranType,P.ID As ItemID,P.Size,P.Product_Code,P.Product_name,P.Product_desc,P.unit,Quantity * -1,P.main_category, P.sub_category
                    From transaction_purchasereturndetail H Inner join inventory_add_products P On H.item_id_id = P.id
                    union all
                    Select 'Sale' As TranType,P.ID AS ItemID,P.Size,P.Product_Code,P.Product_name,P.Product_desc,P.unit,Quantity * -1,P.main_category, P.sub_category
                    From transaction_saledetail H Inner join inventory_add_products P On H.item_id_id = P.id
                    union all
                    Select 'Sale Return' As TranType,P.ID AS ItemID,P.Size,P.Product_Code,P.Product_name,P.Product_desc,P.unit,Quantity,P.main_category, P.sub_category
                    From transaction_salereturndetail H Inner join inventory_add_products P On H.item_id_id = P.id
                    ) As tblTemp
                    Group by Item_Code
                    ''')
    row = cursor.fetchall()
    return render(request, 'inventory/item_stock.html',{'row':row,'allow_customer_roles':allow_customer_roles,'allow_supplier_roles':allow_supplier_roles,'allow_transaction_roles':allow_transaction_roles,
    'permission':permission,'allow_inventory_roles':allow_inventory_roles,    'allow_report_roles':report_roles(request.user),'is_superuser':request.user.is_superuser})


@login_required
@user_passes_test(allow_inventory_add)
def new_item_stock(request):
    allow_customer_roles = customer_roles(request.user)
    allow_supplier_roles = supplier_roles(request.user)
    allow_transaction_roles = transaction_roles(request.user)
    allow_inventory_roles = inventory_roles(request.user)
    return render(request, 'inventory/new_item_stock.html',{'allow_customer_roles':allow_customer_roles,'allow_supplier_roles':allow_supplier_roles,'allow_transaction_roles':allow_transaction_roles,'allow_inventory_roles':allow_inventory_roles,    'allow_report_roles':report_roles(request.user),'is_superuser':request.user.is_superuser})


@login_required
@user_passes_test(allow_inventory_add)
def add_product(request):
    id = request.POST.get('id', False)
    if id:
        sub_categories_list = SubCategory.objects.filter(main_category_id = id).all()
        list = serializers.serialize('json',sub_categories_list)
        print("Hamza")
        return JsonResponse({"list":list})
    serial_no = 0
    allow_customer_roles = customer_roles(request.user)
    allow_supplier_roles = supplier_roles(request.user)
    allow_transaction_roles = transaction_roles(request.user)
    allow_inventory_roles = inventory_roles(request.user)
    get_item_code = Add_products.objects.last()
    main_categories = Category.objects.all()
    sub_categories = SubCategory.objects.all()
    if get_item_code:
        get_item_code = get_item_code.product_code
        serial_no = int(get_item_code) + 1
    else:
        serial_no = '1001'
    product_name = request.POST.get('product_name',False)
    product_desc = request.POST.get('product_desc',False)
    type = request.POST.get('type',False)
    size = request.POST.get('size',False)
    if product_name and product_desc and type and size:
        type = request.POST.get('type',False)
        size = request.POST.get('size',False)
        product_name = request.POST.get('product_name',False)
        product_desc = request.POST.get('product_desc',False)
        opening_stock = request.POST.get('opening_stock',False)
        unit = request.POST.get('unit',False)
        main_category_id = Category.objects.filter(main = type).first()
        sub_category_id = SubCategory.objects.filter(sub = size).first()
        return JsonResponse({"product_name":product_name,"type":type,"size":size,"product_desc": product_desc,'unit':unit,'opening_stock':opening_stock,'main_category_id':main_category_id.id, 'sub_category_id':sub_category_id.id})
    if request.method == 'POST':
        items = json.loads(request.POST.get('items'))
        for value in items:
            item_code = str(serial_no)
            main_category_id = Category.objects.get(id = value["main_category_id"])
            sub_category_id = SubCategory.objects.get(id = value["sub_category_id"])
            new_products = Add_products(product_code = item_code, product_name = value["item_name"], product_desc = value["item_description"],unit = value["unit"], size = value["size"], type = "" ,opening_stock = value["opening_stock"], user_id = request.user ,main_category_id = main_category_id, sub_category_id = sub_category_id, main_category = main_category_id.main, sub_category = sub_category_id.sub )
            new_products.save()
            serial_no = int(serial_no) + 1
        return JsonResponse({"result":"success"})
    return render(request, 'inventory/add_product.html',{'main_categories':main_categories,'sub_categories':sub_categories,'allow_customer_roles':allow_customer_roles,'allow_supplier_roles':allow_supplier_roles,'allow_transaction_roles':allow_transaction_roles,'allow_inventory_roles':allow_inventory_roles,    'allow_report_roles':report_roles(request.user),'is_superuser':request.user.is_superuser})


@login_required
@user_passes_test(allow_inventory_edit)
def edit_item(request,pk):
    allow_customer_roles = customer_roles(request.user)
    allow_supplier_roles = supplier_roles(request.user)
    allow_transaction_roles = transaction_roles(request.user)
    allow_inventory_roles = inventory_roles(request.user)
    all_detail = Add_products.objects.filter(id = pk).first()
    main_categories = Category.objects.all()
    sub_categories = SubCategory.objects.filter(main_category_id = all_detail.main_category_id)
    if request.method == "POST":
        main_category = request.POST.get('main_category')
        sub_category = request.POST.get('sub_category')
        size = request.POST.get('size')
        product_desc = request.POST.get('product_desc')
        select_unit = request.POST['unit']
        opening_stock = request.POST.get('opening_stock')
        main = Category.objects.filter(id = main_category).first()
        sub = SubCategory.objects.filter(id = sub_category).first()
        product_name = main.main+" "+sub.sub+" "+size
        all_detail.sub_category_id = sub
        all_detail.sub_category = sub.sub
        all_detail.size = size
        all_detail.product_name = product_name

Supply_Chain_Proj/inventory/templates/inventory/add_product.html
{% extends "supplier/base.html" %}
{% load crispy_forms_tags %}
{% block body %}

<div class="card" style="width: 100%;">
<div class="card-header">
  <h4>Add Item</h4>
</div>
<ul class="list-group list-group-flush">
<form id="add-item-form" action="" method="post" autocomplete="off">
  <li class="list-group-item">
      {% csrf_token %}
      <div class="form-row">
        <div class="form-group col-md-2">
          <label for="">Select Main Category</label>
          <select class="form-control form-control-sm main_drop" id="main_category">
            <option value="">Select:</option>
            {% for value in main_categories %}
            <option value="{{value.id}}">{{value.main}}</option>
            {% endfor %}
          </select>
        </div>
        <div class="form-group col-md-2">
          <label for="">Select Sub Category</label>
          <select class="form-control form-control-sm" id="sub_category">
          </select>
        </div>
        <div class="form-group col-md-1">
          <label for="">Size</label>
          <input type="text" class="form-control form-control-sm"  id="size">
        </div>
        <div class="form-group col-md-3">
          <label for="">Description</label>
          <textarea name="name" class="form-control form-control-sm" rows="" cols="25" id="product_desc" style="height:30px; width:275px;"></textarea>
        </div>
        <div class="form-group col-md-2">
          <label for="">Unit</label>
          <select class="form-control form-control-sm" id="select_unit" >
            <option value="">FT</option>
            <option value="">MTR</option>
            <option value="">EA.length</option>
            <option value="">NOS.</option>
            <option value="">PCS.</option>
            <option value="">INCHES</option>
            <option value="">P.DOZ</option>
            <option value="">PAIR</option>
            <option value="">TINS.</option>
          </select>
        </div>
        <div class="form-group col-md-2">
          <label for="">Opening Stock</label>
          <input type="text" class="form-control form-control-sm" id="opening_stock" value="0">
        </div>
      </div>
      <div class="table-title">
        <div class="text-right">
            <button type="button" class="btn btn-info add-new-row"><i class="fa fa-plus"></i> Add New</button>
        </div>
      </div>
      <br>
</li>
<li class="list-group-item">
  <div class="table table-responsive">
    <table class="table table-bordered" id="add-item-table">
          <thead>
              <tr>
                  <th width="130px">S. No</th>
                  <th width="130px">Main Category</th>
                  <th width="130px">Sub Category</th>
                  <th width="200px">Item Name</th>
                  <th width="250px">Item Description</th>
                  <th width="100px">Size</th>
                  <th width="100px">Unit</th>
                  <th width="100px">Opening Stock</th>
                  <th>Action</th>
              </tr>
          </thead>
          <tbody>
          </tbody>
      </table>
    </div>
    <div class="text-center">
      <button type="submit" class="btn btn-outline-primary">Submit <small>(Items)</small></button>
    </div>
  </li>
  </form>
</ul>
</div>


{% endblock body %}

Supply_Chain_Proj/inventory/templates/inventory/category_and_type.html
{% extends "supplier/base.html" %}
{% load crispy_forms_tags %}
{% block body %}

<div class="card" style="width: 100%;">
<div class="card-header">
  <h4>Item Stock</h4>
</div>
<ul class="list-group list-group-flush">
  <li class="list-group-item">
    <br>
    <ul style="list-style-type:none;" class="messages">
      {% if messages %}
        {% for msg in messages %}
          <li>
            <div class="alert {{msg.level_tag}}">
              {{msg.message}}
            </div>
          </li>
        {% endfor %}
      {% endif %}
    </ul>
    <div class="input-group">
      <div class="col-md-12">
        <a role="button" href="" style="float:right;" class="btn btn-outline-secondary" name="button" data-toggle="modal" data-target="#addCategoryModal"><i class="fas fa-plus"></i> Add New</a>
      </div>
    </div>
    <h4>Main Category</h4>

  <div class="table table-responsive">
    <table class="table table-bordered sort" id="dataTable">
        <thead>
            <tr>
                <th width="40px">S NO.</th>
                <th>Main Category Code</th>
                <th >Main Category Name</th>
                <td>Action</td>
            </tr>
        </thead>
        <tbody>
          {% for value in main_categories %}
          <tr>
              <td>{{forloop.counter}}</td>
              <td style="display:none;">{{value.id}}</td>
              <td>{{value.category_code}}</td>
              <td>{{value.main}}</td>
  			      <td>
                <a class="edit_list" data-toggle="modal" data-target="#editCategoryModal"><i class="material-icons">&#xE254;</i></a>
                <a class="delete_item_row" href="{% url 'delete-categories' pk=value.id %}" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
              </td>
          </tr>
          {% endfor %}
        </tbody>
    </table>
  </div>
  </li>
</ul>

<ul class="list-group list-group-flush">
  <li class="list-group-item">
    <div class="input-group">
      <div class="col-md-12">
        <a role="button" href="" style="float:right;" class="btn btn-outline-secondary" name="button" data-toggle="modal" data-target="#addCategoryModalSub"><i class="fas fa-plus"></i> Add New</a>
      </div>
    </div>
    <h4>Sub Category</h4>
    <div class="table table-responsive">
    <table class="table table-bordered sort" id="dataTable">
        <thead>
            <tr>
                <th width="40px">S NO.</th>
                <th width="60px">Main Category Name</th>
                <th >Sub Category Code</th>
                <th>Sub Category Name</th>
                <td>Action</td>
            </tr>
        </thead>
        <tbody>
          {% for value in sub_categories %}
          <tr>
              <td>{{forloop.counter}}</td>
              <td style="display:none;">{{value.id}}</td>
              <td style="display:none;">{{value.main_category_id.id}}</td>
              <td>{{value.main_category_id.main}}</td>
              <td>{{value.sub_category_code}}</td>
              <td>{{value.sub}}</td>
              <td>
                <a class="edit_list" data-toggle="modal" data-target="#editCategoryModalSub"><i class="material-icons">&#xE254;</i></a>
                <a class="delete_item_row" href="{% url 'delete-sub-categories' pk=value.id %}" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
              </td>
          </tr>
          {% endfor %}
        </tbody>
    </table>
  </div>
  </li>
</ul>
</div>

      <div class="modal fade" id="addCategoryModal">
        <div class="modal-dialog">
          <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
              <h4 class="modal-title">Add Main Category</h4>
              <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
           <form action="{% url 'main-categories' %}" method="post"  autocomplete="off">
             {% csrf_token %}
            <div class="modal-body">
                <div class="form-row">
                  <div class="form-group col-md-12">
                    <label for="">Main Category Name</label>
                    <!-- <input type="text" style="display:none;" class="form-control form-control-sm" required name="edit" id="id_edit"> -->
                    <input type="text" class="form-control form-control-sm" required name="main_category_name" id="">
                  </div>
                 </div>
            </div>
            <!-- Modal footer -->
            <div class="modal-footer">
              <input type="submit" class="btn btn-success" value="Submit"/>
            </div>
          </form>
          <!-- <form class="" action="index.html" method="post">
          </form> -->
          </div>
        </div>
      </div>


     <div class="modal fade" id="editCategoryModal">
       <div class="modal-dialog">
         <div class="modal-content">

           <!-- Modal Header -->
           <div class="modal-header">
             <h4 class="modal-title">Edit Main Category</h4>
             <button type="button" class="close" data-dismiss="modal">&times;</button>
           </div>

           <!-- Modal body -->
          <form action="{% url 'edit-main-categories' %}" method="post"  autocomplete="off">
            {% csrf_token %}
           <div class="modal-body">
               <div class="form-row">
                 <div class="form-group col-md-12">
                   <label for="">Main Category Code</label>
                   <input type="text" readonly class="form-control form-control-sm" name="main_category_code" id="main_category_code">
                   <br>
                    <label for="">Main Category Name</label>
                   <input type="text" class="form-control form-control-sm" required name="main_category_name_edit" id="main_category_name_edit">
                 </div>
                </div>
           </div>
           <!-- Modal footer -->
           <div class="modal-footer">
             <input type="submit" class="btn btn-success" value="Submit"/>
           </div>
         </form>
         <!-- <form class="" action="index.html" method="post">
         </form> -->
         </div>
       </div>
     </div>


     <div class="modal fade" id="addCategoryModalSub">
       <div class="modal-dialog">
         <div class="modal-content">

           <!-- Modal Header -->
           <div class="modal-header">
             <h4 class="modal-title">Add Sub Category</h4>
             <button type="button" class="close" data-dismiss="modal">&times;</button>
           </div>

           <!-- Modal body -->
          <form action="{% url 'sub-categories' %}" method="post"  autocomplete="off">
            {% csrf_token %}
           <div class="modal-body">
             <div class="form-row">
               <div class="form-group col-md-12">
                 <label for="">Select Main Category</label>
                 <select class="form-control" name="main_category">
                   {% for value in main_categories %}
                   <option value="{{value.id}}">{{value.main}}</option>
                   {% endfor %}
                 </select>
               </div>
              </div>
               <div class="form-row">
                 <div class="form-group col-md-12">
                   <label for="">Sub Category Name</label>
                   <!-- <input type="text" style="display:none;" class="form-control form-control-sm" required name="edit" id="id_edit"> -->
                   <input type="text" class="form-control form-control-sm" required name="sub_category_name" id="">
                 </div>
                </div>
           </div>
           <!-- Modal footer -->
           <div class="modal-footer">
             <input type="submit" class="btn btn-success" value="Submit"/>
           </div>
         </form>
         <!-- <form class="" action="index.html" method="post">
         </form> -->
         </div>
       </div>
     </div>


    <div class="modal fade" id="editCategoryModalSub">
      <div class="modal-dialog">
        <div class="modal-content">

          <!-- Modal Header -->
          <div class="modal-header">
            <h4 class="modal-title">Edit Sub Category</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>

          <!-- Modal body -->
         <form action="{% url 'edit-sub-categories' %}" method="post"  autocomplete="off">
           {% csrf_token %}
            <div class="modal-body">
                <div class="form-row">
                  <div class="form-group col-md-12">
                    <label for="">Sub Category Code</label>
                    <input type="text" readonly class="form-control form-control-sm" name="sub_category_code" id="sub_category_code">
                  </div>
                    <div class="form-group col-md-12">
                      <label for="">Select Main Category</label>
                      <select class="form-control" name="main_category">
                        {% for value in main_categories %}
                        <option value="{{value.id}}">{{value.main}}</option>
                        {% endfor %}
                      </select>
                    </div>
                  <div class="form-group col-md-12">
                     <label for="">Main id</label>
                    <input type="text" class="form-control form-control-sm" readonly name="main_category_id" id="main_category_id">
                  </div>
                  <div class="form-group col-md-12">
                     <label for="">Sub id</label>
                    <input type="text" class="form-control form-control-sm" readonly name="sub_category_id" id="sub_category_id">
                  </div>
                  <div class="form-group col-md-12">
                     <label for="">Sub Category Name</label>
                    <input type="text" class="form-control form-control-sm" required name="sub_category_name_edit" id="sub_category_name_edit">
                  </div>
                 </div>
            </div>
          <!-- Modal footer -->
          <div class="modal-footer">
            <input type="submit" class="btn btn-success" value="Submit"/>
          </div>
        </form>
        <!-- <form class="" action="index.html" method="post">
        </form> -->
        </div>
      </div>
    </div>



{% endblock body %}

Supply_Chain_Proj/inventory/templates/inventory/item_stock.html
{% extends "supplier/base.html" %}
{% load crispy_forms_tags %}
{% block body %}

<div class="card" style="width: 100%;">
<div class="card-header">
  <h4>Item Stock</h4>
</div>
<ul class="list-group list-group-flush">
  <li class="list-group-item">
    <br>
    <ul style="list-style-type:none;" class="messages">
      {% if messages %}
        {% for msg in messages %}
          <li>
            <div class="alert {{msg.level_tag}}">
              {{msg.message}}
            </div>
          </li>
        {% endfor %}
      {% endif %}
    </ul>
    <br>
    <div class="table table-responsive">
    <table class="table table-bordered sort" id="dataTable">
        <thead>
            <tr>
                <th width="40px">S NO.</th>
                <th width="10px">Size</th>
                <th width="70px">Item Code</th>
                <th width="70px">Item Name</th>
                <th width="100px">Item Description</th>
                <th width="70px">Inventory Stock</th>
                <th width="70px">Unit</th>
                <td>Action</td>
            </tr>
        </thead>
        <tbody>
          {% for value in row %}
          <tr>
              <td>{{forloop.counter}}</td>
              <td>{{value.1}}</td>
              <td>{{value.2}}</td>
              <td>{{value.8}} {{value.9}} {{value.1}}</td>
              <td><pre>{{value.4}}</pre></td>
              <td>{{value.7}}</td>
              <td>{{value.5}}</td>
  			      <td>
                {% if permission.edit == 1 %}
                <a class="edit_list" href="{% url 'edit-item' pk=value.0 %}" data-toggle=""><i class="material-icons">&#xE254;</i></a>
                {% endif %}

                {% if permission.delete == 1 %}
                <a class="delete_item_row" href="{% url 'delete-item' pk=value.0 %}" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
                {% endif %}
              </td>
          </tr>
          {% endfor %}
        </tbody>
    </table>
  </div>
  </li>
</ul>
</div>


{% endblock body %}